const $=s=>document.querySelector(s);let state={},destinations=[],camera='chase';
const validated=new Set(['mcdonalds_delivery']);
function worldToMap(x,y,c){const pad=28,w=c.clientWidth-pad*2,h=c.clientHeight-pad*2;return[pad+(x+260)/500*w,pad+(120-y)/250*h]}
function drawMap(){const c=$('#map'),d=devicePixelRatio||1;c.width=c.clientWidth*d;c.height=c.clientHeight*d;const x=c.getContext('2d');x.scale(d,d);let w=c.clientWidth,h=c.clientHeight;x.fillStyle='#0a1411';x.fillRect(0,0,w,h);x.strokeStyle='#1d3129';x.lineWidth=1;for(let i=0;i<12;i++){x.beginPath();x.moveTo(i*w/11,0);x.lineTo(i*w/11,h);x.stroke()}for(let i=0;i<8;i++){x.beginPath();x.moveTo(0,i*h/7);x.lineTo(w,i*h/7);x.stroke()}x.strokeStyle='#31483e';x.lineWidth=14;[[-210,-88,-150,-88],[-150,-115,-150,20],[-150,0,190,0],[150,0,172,68]].forEach(a=>{let p=worldToMap(a[0],a[1],c),q=worldToMap(a[2],a[3],c);x.beginPath();x.moveTo(...p);x.lineTo(...q);x.stroke()});x.fillStyle='#172822';for(let i=0;i<28;i++){let px=60+(i*83)%Math.max(100,w-120),py=35+(i*47)%Math.max(100,h-80);x.fillRect(px,py,24+(i%4)*7,18+(i%3)*8)}let trail=state.trajectory||[];if(trail.length>1){x.strokeStyle='#49a8ff';x.lineWidth=3;x.beginPath();trail.forEach((p,i)=>{let q=worldToMap(p[0],p[1],c);i?x.lineTo(...q):x.moveTo(...q)});x.stroke()}if(state.selected_destination){let p=worldToMap(state.selected_destination.x,state.selected_destination.y,c);x.strokeStyle='#ffc857';x.lineWidth=3;x.beginPath();x.arc(...p,11,0,7);x.stroke()}if(state.odom){let p=worldToMap(state.odom[0],state.odom[1],c);x.fillStyle='#b7f34a';x.shadowColor='#b7f34a';x.shadowBlur=14;x.beginPath();x.arc(...p,7,0,7);x.fill();x.shadowBlur=0}}
function phaseInfo(m){if(m.startsWith('WAITING'))return['목적지를 선택해 주세요','선택 전에는 드론이 물류센터에서 대기합니다.'];if(m.startsWith('TAKEOFF'))return['순항 고도로 상승 중','22m 높이까지 올라가 전방 카메라를 활성화합니다.'];if(m.startsWith('CRUISE STOP'))return['안전을 위해 정지','센서가 없거나 통과 가능한 경로를 찾지 못했습니다.'];if(m.startsWith('CRUISE REOBSERVE'))return['시야를 바꾸어 다시 탐색','막힌 공간에서 회전하며 새로운 depth를 수집합니다.'];if(m.startsWith('CRUISE'))return['목적지로 자율 비행 중','Depth 비용지도에서 충돌 없는 2스텝 경로를 반복 선택합니다.'];if(m.startsWith('ARRIVE'))return['목적지 상공에 도착','착륙 카메라가 잘 보이는 12m까지 낮춥니다.'];if(m.startsWith('SCAN'))return['안전한 착륙 공간 탐색','DINOv2 특징과 거리 정보로 장애물을 제외하고 후보를 채점합니다.'];if(m.startsWith('DESCEND'))return['선택한 지점으로 하강','새 장애물이 나타나면 착륙점을 다시 평가합니다.'];if(m.startsWith('LANDED'))return['배송지 착륙 완료','비전으로 선택한 안전 지점에 도착했습니다.'];return['시스템 연결 중','ROS 데이터 수신을 기다립니다.']}
async function refresh(){try{state=await fetch('/api/state').then(r=>r.json());$('#dot').classList.toggle('on',state.connected);$('#connection').textContent=state.connected?'ROS 실시간 연결':'ROS 연결 대기';$('#phase').textContent=(state.mission||'—').split(' ')[0];let [a,b]=phaseInfo(state.mission||'');$('#decision').textContent=a;$('#reason').textContent=b;$('#alt').textContent=state.odom?state.odom[2].toFixed(1):'—';$('#position').textContent=state.odom?`${state.odom[0].toFixed(1)}, ${state.odom[1].toFixed(1)}`:'—';$('#planner').textContent=state.planning?.status||'—';$('#selected').textContent=state.selected_destination?.label||'선택 전';drawMap();const img=$('#camera');img.src=`/api/${camera}.jpg?t=${Date.now()}`;img.style.display=state.connected?'block':'none'}catch(e){$('#connection').textContent='대시보드 서버 연결 끊김'}}
function renderDestinations(){const el=$('#destinations');el.innerHTML='';destinations.filter(d=>!d.requires_elevation_support).sort((a,b)=>validated.has(b.id)-validated.has(a.id)).slice(0,8).forEach(d=>{let card=document.createElement('div'),ok=validated.has(d.id);card.className='destination '+(ok?'':'locked');card.innerHTML=`<small>${ok?'FLIGHT VALIDATED':'EXPERIMENTAL'}</small><b>${d.label}</b><p>${d.note}</p>`;if(ok)card.onclick=()=>selectDestination(d,card);el.append(card)})}
async function selectDestination(d,card){try{let r=await fetch('/api/destination',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:d.id})}),j=await r.json();if(!r.ok)throw Error(j.error);document.querySelectorAll('.destination').forEach(x=>x.classList.remove('active'));card.classList.add('active');toast(`${d.label} 배송을 시작합니다`)}catch(e){toast(e.message)} }
function toast(t){let e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');camera=b.dataset.camera});
fetch('/api/destinations').then(r=>r.json()).then(d=>{destinations=d;renderDestinations()});addEventListener('resize',drawMap);setInterval(refresh,500);refresh();
